// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Phoenix.Infrastructure.Persistence;

#nullable disable

namespace Phoenix.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PhoenixDbContext))]
    [Migration("20260406010430_AddAuthModule")]
    partial class AddAuthModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Phoenix.Application.Common.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("application_users", (string)null);
                });

            modelBuilder.Entity("Phoenix.Domain.Customers.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Phoenix.Domain.Customers.Entities.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("FR");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_addresses", (string)null);
                });

            modelBuilder.Entity("Phoenix.Domain.Products.Entities.PriceTier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPriceHT")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("price_tiers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0001-0001-0000-000000000000"),
                            MaxQuantity = 1999,
                            MinQuantity = 500,
                            ProductVariantId = new Guid("22222222-0001-0001-0000-000000000000"),
                            UnitPriceHT = 0.1500m
                        },
                        new
                        {
                            Id = new Guid("33333333-0001-0002-0000-000000000000"),
                            MaxQuantity = 4999,
                            MinQuantity = 2000,
                            ProductVariantId = new Guid("22222222-0001-0001-0000-000000000000"),
                            UnitPriceHT = 0.1200m
                        },
                        new
                        {
                            Id = new Guid("33333333-0001-0003-0000-000000000000"),
                            MinQuantity = 5000,
                            ProductVariantId = new Guid("22222222-0001-0001-0000-000000000000"),
                            UnitPriceHT = 0.0900m
                        },
                        new
                        {
                            Id = new Guid("33333333-0002-0001-0000-000000000000"),
                            MaxQuantity = 999,
                            MinQuantity = 250,
                            ProductVariantId = new Guid("22222222-0002-0001-0000-000000000000"),
                            UnitPriceHT = 0.1200m
                        },
                        new
                        {
                            Id = new Guid("33333333-0002-0002-0000-000000000000"),
                            MaxQuantity = 4999,
                            MinQuantity = 1000,
                            ProductVariantId = new Guid("22222222-0002-0001-0000-000000000000"),
                            UnitPriceHT = 0.0900m
                        },
                        new
                        {
                            Id = new Guid("33333333-0002-0003-0000-000000000000"),
                            MinQuantity = 5000,
                            ProductVariantId = new Guid("22222222-0002-0001-0000-000000000000"),
                            UnitPriceHT = 0.0700m
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0001-0000-000000000000"),
                            MaxQuantity = 999,
                            MinQuantity = 250,
                            ProductVariantId = new Guid("22222222-0003-0001-0000-000000000000"),
                            UnitPriceHT = 0.1800m
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0002-0000-000000000000"),
                            MaxQuantity = 2999,
                            MinQuantity = 1000,
                            ProductVariantId = new Guid("22222222-0003-0001-0000-000000000000"),
                            UnitPriceHT = 0.1400m
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0000-000000000000"),
                            MinQuantity = 3000,
                            ProductVariantId = new Guid("22222222-0003-0001-0000-000000000000"),
                            UnitPriceHT = 0.1100m
                        },
                        new
                        {
                            Id = new Guid("33333333-0004-0001-0000-000000000000"),
                            MaxQuantity = 499,
                            MinQuantity = 100,
                            ProductVariantId = new Guid("22222222-0004-0001-0000-000000000000"),
                            UnitPriceHT = 0.2200m
                        },
                        new
                        {
                            Id = new Guid("33333333-0004-0002-0000-000000000000"),
                            MaxQuantity = 1999,
                            MinQuantity = 500,
                            ProductVariantId = new Guid("22222222-0004-0001-0000-000000000000"),
                            UnitPriceHT = 0.1800m
                        },
                        new
                        {
                            Id = new Guid("33333333-0004-0003-0000-000000000000"),
                            MinQuantity = 2000,
                            ProductVariantId = new Guid("22222222-0004-0001-0000-000000000000"),
                            UnitPriceHT = 0.1400m
                        },
                        new
                        {
                            Id = new Guid("33333333-0005-0001-0000-000000000000"),
                            MaxQuantity = 199,
                            MinQuantity = 50,
                            ProductVariantId = new Guid("22222222-0005-0001-0000-000000000000"),
                            UnitPriceHT = 0.4500m
                        },
                        new
                        {
                            Id = new Guid("33333333-0005-0002-0000-000000000000"),
                            MaxQuantity = 499,
                            MinQuantity = 200,
                            ProductVariantId = new Guid("22222222-0005-0001-0000-000000000000"),
                            UnitPriceHT = 0.3800m
                        },
                        new
                        {
                            Id = new Guid("33333333-0005-0003-0000-000000000000"),
                            MinQuantity = 500,
                            ProductVariantId = new Guid("22222222-0005-0001-0000-000000000000"),
                            UnitPriceHT = 0.3000m
                        },
                        new
                        {
                            Id = new Guid("33333333-0006-0001-0000-000000000000"),
                            MaxQuantity = 4999,
                            MinQuantity = 1000,
                            ProductVariantId = new Guid("22222222-0006-0001-0000-000000000000"),
                            UnitPriceHT = 0.0800m
                        },
                        new
                        {
                            Id = new Guid("33333333-0006-0002-0000-000000000000"),
                            MaxQuantity = 9999,
                            MinQuantity = 5000,
                            ProductVariantId = new Guid("22222222-0006-0001-0000-000000000000"),
                            UnitPriceHT = 0.0650m
                        },
                        new
                        {
                            Id = new Guid("33333333-0006-0003-0000-000000000000"),
                            MinQuantity = 10000,
                            ProductVariantId = new Guid("22222222-0006-0001-0000-000000000000"),
                            UnitPriceHT = 0.0520m
                        },
                        new
                        {
                            Id = new Guid("33333333-0007-0001-0000-000000000000"),
                            MaxQuantity = 499,
                            MinQuantity = 100,
                            ProductVariantId = new Guid("22222222-0007-0001-0000-000000000000"),
                            UnitPriceHT = 0.3500m
                        },
                        new
                        {
                            Id = new Guid("33333333-0007-0002-0000-000000000000"),
                            MaxQuantity = 1999,
                            MinQuantity = 500,
                            ProductVariantId = new Guid("22222222-0007-0001-0000-000000000000"),
                            UnitPriceHT = 0.2800m
                        },
                        new
                        {
                            Id = new Guid("33333333-0007-0003-0000-000000000000"),
                            MinQuantity = 2000,
                            ProductVariantId = new Guid("22222222-0007-0001-0000-000000000000"),
                            UnitPriceHT = 0.2200m
                        },
                        new
                        {
                            Id = new Guid("33333333-0008-0001-0000-000000000000"),
                            MaxQuantity = 1999,
                            MinQuantity = 500,
                            ProductVariantId = new Guid("22222222-0008-0001-0000-000000000000"),
                            UnitPriceHT = 0.0600m
                        },
                        new
                        {
                            Id = new Guid("33333333-0008-0002-0000-000000000000"),
                            MaxQuantity = 4999,
                            MinQuantity = 2000,
                            ProductVariantId = new Guid("22222222-0008-0001-0000-000000000000"),
                            UnitPriceHT = 0.0480m
                        },
                        new
                        {
                            Id = new Guid("33333333-0008-0003-0000-000000000000"),
                            MinQuantity = 5000,
                            ProductVariantId = new Guid("22222222-0008-0001-0000-000000000000"),
                            UnitPriceHT = 0.0380m
                        },
                        new
                        {
                            Id = new Guid("33333333-0009-0001-0000-000000000000"),
                            MaxQuantity = 1999,
                            MinQuantity = 500,
                            ProductVariantId = new Guid("22222222-0009-0001-0000-000000000000"),
                            UnitPriceHT = 0.0700m
                        },
                        new
                        {
                            Id = new Guid("33333333-0009-0002-0000-000000000000"),
                            MaxQuantity = 4999,
                            MinQuantity = 2000,
                            ProductVariantId = new Guid("22222222-0009-0001-0000-000000000000"),
                            UnitPriceHT = 0.0550m
                        },
                        new
                        {
                            Id = new Guid("33333333-0009-0003-0000-000000000000"),
                            MinQuantity = 5000,
                            ProductVariantId = new Guid("22222222-0009-0001-0000-000000000000"),
                            UnitPriceHT = 0.0420m
                        },
                        new
                        {
                            Id = new Guid("33333333-0010-0001-0000-000000000000"),
                            MaxQuantity = 4999,
                            MinQuantity = 1000,
                            ProductVariantId = new Guid("22222222-0010-0001-0000-000000000000"),
                            UnitPriceHT = 0.0400m
                        },
                        new
                        {
                            Id = new Guid("33333333-0010-0002-0000-000000000000"),
                            MaxQuantity = 9999,
                            MinQuantity = 5000,
                            ProductVariantId = new Guid("22222222-0010-0001-0000-000000000000"),
                            UnitPriceHT = 0.0320m
                        },
                        new
                        {
                            Id = new Guid("33333333-0010-0003-0000-000000000000"),
                            MinQuantity = 10000,
                            ProductVariantId = new Guid("22222222-0010-0001-0000-000000000000"),
                            UnitPriceHT = 0.0250m
                        });
                });

            modelBuilder.Entity("Phoenix.Domain.Products.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionFr")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasDefaultValue("");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("HasExpressDelivery")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBulkOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCustomizable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEcoFriendly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFoodApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGourmetRange")
                        .HasColumnType("boolean");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("SoldByWeight")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0001-0000-0000-000000000000"),
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionFr = "Sac en papier kraft naturel avec anses torsadées. Format médium idéal pour la vente à emporter en restauration et boulangerie.",
                            Family = "KraftBagHandled",
                            HasExpressDelivery = true,
                            IsActive = true,
                            IsBulkOnly = false,
                            IsCustomizable = true,
                            IsEcoFriendly = true,
                            IsFoodApproved = true,
                            IsGourmetRange = false,
                            NameFr = "Sac kraft avec anses torsadées (M)",
                            Sku = "SAC-KRAFT-TORSADE-M",
                            SoldByWeight = false,
                            UpdatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0002-0000-0000-000000000000"),
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionFr = "Sac kraft à fond carré SOS en format small. Stable, robuste, idéal pour boulangeries et épiceries fines.",
                            Family = "KraftBagSOS",
                            HasExpressDelivery = true,
                            IsActive = true,
                            IsBulkOnly = false,
                            IsCustomizable = true,
                            IsEcoFriendly = true,
                            IsFoodApproved = true,
                            IsGourmetRange = false,
                            NameFr = "Sac kraft SOS fond carré (S)",
                            Sku = "SAC-KRAFT-SOS-S",
                            SoldByWeight = false,
                            UpdatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0003-0000-0000-000000000000"),
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionFr = "Bol kraft rond 500 ml pour plats chauds type soupe, curry ou poke bowl. Certifié contact alimentaire.",
                            Family = "KraftBowl",
                            HasExpressDelivery = true,
                            IsActive = true,
                            IsBulkOnly = false,
                            IsCustomizable = true,
                            IsEcoFriendly = true,
                            IsFoodApproved = true,
                            IsGourmetRange = false,
                            NameFr = "Bol kraft 500 ml",
                            Sku = "BOL-KRAFT-500ML",
                            SoldByWeight = false,
                            UpdatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0004-0000-0000-000000000000"),
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionFr = "Bol chirashi rectangulaire grand format pour sushis, poké et chirashi. Couvercle transparent inclus.",
                            Family = "ChirashiBowl",
                            HasExpressDelivery = false,
                            IsActive = true,
                            IsBulkOnly = false,
                            IsCustomizable = true,
                            IsEcoFriendly = false,
                            IsFoodApproved = true,
                            IsGourmetRange = true,
                            NameFr = "Bol chirashi rectangulaire (L)",
                            Sku = "BOL-CHIRASHI-L",
                            SoldByWeight = false,
                            UpdatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0005-0000-0000-000000000000"),
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionFr = "Boîte pizza en carton ondulé double cannelure 30 cm. Impression intérieure Food-safe, maintien de chaleur optimisé.",
                            Family = "PizzaBox",
                            HasExpressDelivery = true,
                            IsActive = true,
                            IsBulkOnly = false,
                            IsCustomizable = true,
                            IsEcoFriendly = false,
                            IsFoodApproved = true,
                            IsGourmetRange = false,
                            NameFr = "Boîte pizza 30 cm",
                            Sku = "BOITE-PIZZA-30",
                            SoldByWeight = false,
                            UpdatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0006-0000-0000-000000000000"),
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionFr = "Gobelet en carton double paroi 8 oz (24 cl) pour boissons chaudes. Poignée thermique intégrée.",
                            Family = "CoffeeCup",
                            HasExpressDelivery = true,
                            IsActive = true,
                            IsBulkOnly = false,
                            IsCustomizable = true,
                            IsEcoFriendly = false,
                            IsFoodApproved = true,
                            IsGourmetRange = false,
                            NameFr = "Gobelet café 8 oz",
                            Sku = "GOB-CAFE-8OZ",
                            SoldByWeight = false,
                            UpdatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0007-0000-0000-000000000000"),
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionFr = "Plateau polypropylène avec couvercle transparent pour 9 pièces de sushis. Barquette hermétique, empilable.",
                            Family = "SushiTray",
                            HasExpressDelivery = false,
                            IsActive = true,
                            IsBulkOnly = false,
                            IsCustomizable = false,
                            IsEcoFriendly = false,
                            IsFoodApproved = true,
                            IsGourmetRange = true,
                            NameFr = "Plateau sushis 9 pièces",
                            Sku = "PLATEAU-SUSHI-M",
                            SoldByWeight = false,
                            UpdatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0008-0000-0000-000000000000"),
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionFr = "Cornet en papier kraft naturel pour frites et snacks. Format moyen — capacité 220 g. Antigraisse naturel.",
                            Family = "FriesCone",
                            HasExpressDelivery = true,
                            IsActive = true,
                            IsBulkOnly = false,
                            IsCustomizable = true,
                            IsEcoFriendly = true,
                            IsFoodApproved = true,
                            IsGourmetRange = false,
                            NameFr = "Cornet frites moyen",
                            Sku = "CORNET-FRITES-M",
                            SoldByWeight = false,
                            UpdatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0009-0000-0000-000000000000"),
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionFr = "Sachet kraft pour sandwich, bagel et panini. Ouverture facile, fond plat autoportant.",
                            Family = "SandwichBag",
                            HasExpressDelivery = true,
                            IsActive = true,
                            IsBulkOnly = false,
                            IsCustomizable = true,
                            IsEcoFriendly = true,
                            IsFoodApproved = true,
                            IsGourmetRange = false,
                            NameFr = "Sachet sandwich standard",
                            Sku = "SACHET-SANDWICH-STD",
                            SoldByWeight = false,
                            UpdatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0010-0000-0000-000000000000"),
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionFr = "Serviette en papier ouate 2 plis 33×33 cm. Coloris blanc. Idéale pour la restauration rapide et les food trucks.",
                            Family = "Napkin",
                            HasExpressDelivery = true,
                            IsActive = true,
                            IsBulkOnly = true,
                            IsCustomizable = true,
                            IsEcoFriendly = true,
                            IsFoodApproved = true,
                            IsGourmetRange = false,
                            NameFr = "Serviette papier 33×33 cm",
                            Sku = "SERVIETTE-33X33",
                            SoldByWeight = false,
                            UpdatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Phoenix.Domain.Products.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ThumbBlobPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ThumbPublicUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("Phoenix.Domain.Products.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorCount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinimumOrderQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrintSide")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("product_variants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0001-0001-0000-000000000000"),
                            ColorCount = "One",
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumOrderQuantity = 500,
                            NameFr = "Sans impression",
                            PrintSide = "SingleSide",
                            ProductId = new Guid("11111111-0001-0000-0000-000000000000"),
                            Sku = "SAC-KRAFT-TORSADE-M-1C"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0001-0000-000000000000"),
                            ColorCount = "One",
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumOrderQuantity = 250,
                            NameFr = "Sans impression",
                            PrintSide = "SingleSide",
                            ProductId = new Guid("11111111-0002-0000-0000-000000000000"),
                            Sku = "SAC-KRAFT-SOS-S-1C"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-0001-0000-000000000000"),
                            ColorCount = "One",
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumOrderQuantity = 250,
                            NameFr = "Sans impression",
                            PrintSide = "SingleSide",
                            ProductId = new Guid("11111111-0003-0000-0000-000000000000"),
                            Sku = "BOL-KRAFT-500ML-1C"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-0001-0000-000000000000"),
                            ColorCount = "One",
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumOrderQuantity = 100,
                            NameFr = "Sans impression",
                            PrintSide = "SingleSide",
                            ProductId = new Guid("11111111-0004-0000-0000-000000000000"),
                            Sku = "BOL-CHIRASHI-L-1C"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-0001-0000-000000000000"),
                            ColorCount = "Two",
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumOrderQuantity = 50,
                            NameFr = "Impression 2 couleurs recto",
                            PrintSide = "SingleSide",
                            ProductId = new Guid("11111111-0005-0000-0000-000000000000"),
                            Sku = "BOITE-PIZZA-30-2C"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-0001-0000-000000000000"),
                            ColorCount = "One",
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumOrderQuantity = 1000,
                            NameFr = "Sans impression",
                            PrintSide = "SingleSide",
                            ProductId = new Guid("11111111-0006-0000-0000-000000000000"),
                            Sku = "GOB-CAFE-8OZ-1C"
                        },
                        new
                        {
                            Id = new Guid("22222222-0007-0001-0000-000000000000"),
                            ColorCount = "One",
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumOrderQuantity = 100,
                            NameFr = "Standard",
                            PrintSide = "SingleSide",
                            ProductId = new Guid("11111111-0007-0000-0000-000000000000"),
                            Sku = "PLATEAU-SUSHI-M-STD"
                        },
                        new
                        {
                            Id = new Guid("22222222-0008-0001-0000-000000000000"),
                            ColorCount = "One",
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumOrderQuantity = 500,
                            NameFr = "Sans impression",
                            PrintSide = "SingleSide",
                            ProductId = new Guid("11111111-0008-0000-0000-000000000000"),
                            Sku = "CORNET-FRITES-M-1C"
                        },
                        new
                        {
                            Id = new Guid("22222222-0009-0001-0000-000000000000"),
                            ColorCount = "One",
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumOrderQuantity = 500,
                            NameFr = "Sans impression",
                            PrintSide = "SingleSide",
                            ProductId = new Guid("11111111-0009-0000-0000-000000000000"),
                            Sku = "SACHET-SANDWICH-STD-1C"
                        },
                        new
                        {
                            Id = new Guid("22222222-0010-0001-0000-000000000000"),
                            ColorCount = "One",
                            CreatedAtUtc = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumOrderQuantity = 1000,
                            NameFr = "Sans impression",
                            PrintSide = "SingleSide",
                            ProductId = new Guid("11111111-0010-0000-0000-000000000000"),
                            Sku = "SERVIETTE-33X33-1C"
                        });
                });

            modelBuilder.Entity("Phoenix.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Phoenix.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Phoenix.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Phoenix.Application.Common.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Phoenix.Application.Common.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Phoenix.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phoenix.Application.Common.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Phoenix.Application.Common.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Phoenix.Domain.Customers.Entities.CustomerAddress", b =>
                {
                    b.HasOne("Phoenix.Domain.Customers.Entities.Customer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Phoenix.Domain.Products.Entities.PriceTier", b =>
                {
                    b.HasOne("Phoenix.Domain.Products.Entities.ProductVariant", null)
                        .WithMany("PriceTiers")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Phoenix.Domain.Products.Entities.ProductImage", b =>
                {
                    b.HasOne("Phoenix.Domain.Products.Entities.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Phoenix.Domain.Products.Entities.ProductVariant", b =>
                {
                    b.HasOne("Phoenix.Domain.Products.Entities.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Phoenix.Domain.Customers.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Phoenix.Domain.Products.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Phoenix.Domain.Products.Entities.ProductVariant", b =>
                {
                    b.Navigation("PriceTiers");
                });
#pragma warning restore 612, 618
        }
    }
}
